### ISSUE TITLE
Discrepancy between DeFi Pulse and btconethereum.com

### ISSUE THREAD

**Issue by JustinDrake** [ConcourseOpen/DeFi-Pulse-Adapters#120]
There seems to be a significant discrepancy between DeFi Pulse and btconethereum.com regarding the number of BTC on Ethereum. DeFi Pulse is consistently reporting a larger amount.

Right now DeFi Pulse reports 109K BTC, of which all are on Ethereum expect for 1.1K BTC on the Lightning Network. That's a total 107.9K BTC on Ethereum. However, btconethereum.com reports 100.8K BTC. Where does the 7.1K BTC discrepancy come from?

Because btconethereum.com pulls its data straight off the smart contracts' `totalSupply` functions my best guess is that DeFi Pulse has a double-counting bug.

(Apologies if this is the wrong place to submit this issue.)

**Comment by bford21** [comment]
Closing as we are tracking internally
