### ISSUE TITLE
yearn TVL is wrong

### ISSUE THREAD

**Issue by bunkhead** [ConcourseOpen/DeFi-Pulse-Adapters#144]
[Here's](https://docs.google.com/spreadsheets/d/1efyKoycqYzQ0dSgFkZhkm7FC01OGlmQLs2mTLLCpnsY/edit#gid=1169453042) spreadsheet @wir made which shows how to calculate the TVL without double-counting.

Some discussion [here](https://discord.com/channels/750377104826433556/750377457558880358/770977833769369631) and [here](https://discord.com/channels/750377104826433556/750377457558880358/770427212079038494).

I'll be looking into this...

**Comment by bford21** [comment]
Was addressed awhile back with the Yearn team and is now resolved.
