### ISSUE TITLE
Settle on either package-lock.json or yarn.lock

### ISSUE THREAD

**Issue by paulrberg** [ConcourseOpen/DeFi-Pulse-Adapters#322]
## Description

Having a `package-lock.json` and a `yarn.lock` file at the same time is [not recommended](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/):

> We highly recommend you to delete the `package-lock.json` file if you decide to use yarn in order to avoid future confusion and possible consistency issues.

## Solution

Delete either the `package-lock.json` or the `yarn.lock` file.

**Comment by paulrberg** [comment]
😕

**Comment by bford21** [comment]
> 😕

Closed because we've removed our yarn.lock file and settled on package-lock.json thanks for raising this issue!

**Comment by paulrberg** [comment]
Ah haha, okay!
